DROP DATABASE IF EXISTS grhdb;
CREATE DATABASE grhdb;

DROP DATABASE IF EXISTS testdb;
CREATE DATABASE testdb;

CREATE TABLE users
(
	id int NOT NULL AUTO_INCREMENT,
	user_name varchar(100) NOT NULL,
	date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE time_create DATETIME NOT NULL,
	PRIMARY KEY (id)
);
